services:
  namenode:
    image: bde2020/hadoop-namenode:${HADOOP_IMAGE_VERSION}
    platform: ${PLATFORM}
    container_name: namenode
    hostname: namenode
    restart: unless-stopped
    ports:
      - "9870:9870"   # Web UI HDFS
      - "9000:9000"   # RPC
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
    env_file:
      - ./hadoop.env
    networks: [sabd-net]

  datanode:
    image: bde2020/hadoop-datanode:${HADOOP_IMAGE_VERSION}
    platform: ${PLATFORM}
    container_name: datanode
    hostname: datanode
    restart: unless-stopped
    volumes:
      - hdfs_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks: [sabd-net]

  spark-master:
    build: ./spark
    image: sabd-spark:${SPARK_IMAGE_VERSION}
    platform: ${PLATFORM}
    container_name: spark-master
    hostname: spark-master
    restart: unless-stopped
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    working_dir: /opt/spark/jobs
    ports:
      - "8080:8080"   # Web UI Spark Master
      - "7077:7077"
      - "4040:4040"# RPC Spark Master
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./nifi/config:/opt/hadoop/conf
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/conf
    depends_on:
      - namenode
    networks: [sabd-net]

  spark-worker:
    image: sabd-spark:${SPARK_IMAGE_VERSION}
    pull_policy: never
    platform: ${PLATFORM}
    container_name: spark-worker
    hostname: spark-worker
    restart: unless-stopped
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./nifi/config:/opt/hadoop/conf
    environment:
      - HADOOP_CONF_DIR=/opt/hadoop/conf
      - SPARK_WORKER_MEMORY=1536m
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    networks: [sabd-net]

  nifi:
    image: apache/nifi:${NIFI_IMAGE_VERSION}
    platform: ${PLATFORM}
    container_name: nifi
    hostname: nifi
    restart: unless-stopped
    ports:
      - "8443:8443"   # Web UI NiFi (HTTPS)
    volumes:
      - ./data:/opt/nifi/data
      - ./nifi/config:/opt/nifi/nifi-config
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
    depends_on:
      - namenode
    networks: [sabd-net]

  redis:
    image: redis:7.2-alpine
    platform: ${PLATFORM}
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"   # Redis
    networks: [sabd-net]

  grafana:
    image: grafana/grafana-oss:10.4.2
    platform: ${PLATFORM}
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"   # Web UI Grafana
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/q1.json
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - redis
    networks: [sabd-net]

networks:
  sabd-net:
    driver: bridge

volumes:
  hdfs_namenode:
  hdfs_datanode:
  grafana_data:
